---
- name: "Installing useful github repos"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.location }}"
  loop:
    - { repo: "https://github.com/danielmiessler/SecLists", location: "/opt/wordlists/SecLists" }
    - { repo: "https://github.com/kkrypt0nn/wordlists", location: "/opt/wordlists/wordlists" }
    - { repo: "https://github.com/the-xentropy/samlists", location: "/opt/wordlists/samlists" }
    - { repo: "https://github.com/Karanxa/Bug-Bounty-Wordlists", location: "/opt/wordlists/Bug-Bounty-Wordlists" }
    - { repo: "https://github.com/fuzzdb-project/fuzzdb", location: "/opt/wordlists/fuzzdb" }
    - { repo: "https://github.com/Bo0oM/fuzz.txt", location: "/opt/wordlists/fuzz.txt" }
    - { repo: "https://github.com/lobuhi/byp4xx", location: "/opt/wordlists/byp4xx" }
    - { repo: "https://github.com/orwagodfather/My-WordLISTs", location: "/opt/wordlists/My-WordLISTs" }
    - { repo: "https://github.com/swisskyrepo/PayloadsAllTheThings", location: "/opt/wordlists/PayloadsAllTheThings" }
    - { repo: "https://github.com/g0ldencybersec/sus_params", location: "/opt/wordlists/sus_params" }
    - { repo: "https://github.com/maK-/parameth/", location: "/opt/wordlists/parameth" }
  become: true
  ignore_errors: true
